routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false
]);

Route::middleware(['auth'])
    ->group(function () {
        Route::get('/', 'HomeController@index')->name('home');

        // Clients
        Route::get('clients/filter', 'ClientController@filter')->name('clients.filter');
        Route::post('clients/bulk-destroy', 'ClientController@bulkDestroy')->name('clients.bulk-destroy');
        Route::resource('clients', 'ClientController');

        // Products
        Route::get('products/filter', 'ProductController@filter')->name('products.filter');
        Route::post('products/bulk-destroy', 'ProductController@bulkDestroy')->name('products.bulk-destroy');
        Route::resource('products', 'ProductController');

        // Orders
        Route::get('orders/add-to-cart', 'OrderController@addToCart');
        Route::get('orders/remove-from-cart', 'OrderController@removeFromCart');
        Route::get('orders/filter', 'OrderController@filter')->name('orders.filter');
        Route::get('orders/paginate', 'OrderController@paginate')->name('orders.paginate');
        Route::post('orders/bulk-destroy', 'OrderController@bulkDestroy')->name('orders.bulk-destroy');
        Route::resource('orders', 'OrderController');
});

resources/views/partials/alert.blade.php
@if (session('success') || (isset($type) && $type == 'success'))
    <div class="alert alert-success alert-dismissible fade show border-0" role="alert">
        {{ session('success') ?? $message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@elseif (session('warning') || (isset($type) && $type == 'warning'))
    <div class="alert alert-warning alert-dismissible fade show border-0" role="alert">
        {{ session('warning') ?? $message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@elseif (session('danger') || (isset($type) && $type == 'danger'))
    <div class="alert alert-danger alert-dismissible fade show border-0" role="alert">
        {{ session('danger') ?? $message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@elseif (session('info') || (isset($type) && $type == 'info'))
    <div class="alert alert-info alert-dismissible fade show border-0" role="alert">
        {{ session('info') ?? $message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/partials/bulk-actions.blade.php
<div class="form-group mb-0">
    <label for="bulk">Ações em Massa</label>
    <select id="bulk-option" class="form-control form-control-sm" name="bulk" id="bulk">
        <option value="" selected>Selecione</option>

        @foreach ($actions as $key => $action)
            <option value="{{ $key }}" data-action="{{ $action }}">Remover</option>
        @endforeach
    </select>
</div>

<button id="bulk-action" class="btn btn-sm btn-secondary ml-2" type="button">Aplicar</button>

resources/views/partials/filter.blade.php
<div class="form-group">
    <label for="filter">
        <b>Filtrar</b> 
    
        @if (isset($count_results) && $count_results)
            (Resultados: {{ $count_results }})
        @endif
    </label>

    <div class="input-group mb-3">
        <input id="filter" class="form-control" type="text" name="search" value="{{ request()->get('search') }}" placeholder="{{ $placeholder ?? '' }}" aria-describedby="button-addon-search">

        <div class="input-group-append">
            <button class="btn btn-success" type="submit" id="button-addon-search">Filtrar</button>
        </div>
    </div>
</div>

@isset($options)    
    @foreach ($options as $key => $option)    
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" name="filter[]" value="{{ $key }}" id="{{ $key }}" {{ array_key_exists('filter', request()->all()) && in_array($key, request()->get('filter')) ? 'checked' : '' }}>
            <label class="form-check-label" for="{{ $key }}">
                {{ $option }}            
            </label>
        </div>
    @endforeach
@endisset

resources/views/partials/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-primary">
    <div class="container">
        <a class="navbar-brand text-white d-inline-none-md" href="{{ route('home') }}">Teste Pague Logo</a>
        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link text-white" href="{{ route('home') }}">Home</a>
                </li>

                <!-- Clients -->
                <li class="nav-item dropdown">
                    <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdownClients" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Clientes
                    </a>

                    <div class="dropdown-menu" aria-labelledby="navbarDropdownClients">
                        <a class="dropdown-item" href="{{ route('clients.index') }}">Ver Todos</a>
                        <a class="dropdown-item" href="{{ route('clients.create') }}">Adicionar Novo</a>
                    </div>
                </li>

                <!-- Products -->
                <li class="nav-item dropdown">
                    <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdownProducts" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Produtos
                    </a>

                    <div class="dropdown-menu" aria-labelledby="navbarDropdownProducts">
                        <a class="dropdown-item" href="{{ route('products.index') }}">Ver Todos</a>
                        <a class="dropdown-item" href="{{ route('products.create') }}">Adicionar Novo</a>
                    </div>
                </li>

                <!-- Orders -->
                <li class="nav-item dropdown">
                    <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdownOrders" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Pedidos
                    </a>

                    <div class="dropdown-menu" aria-labelledby="navbarDropdownOrders">
                        <a class="dropdown-item" href="{{ route('orders.index') }}">Ver Todos</a>
                        <a class="dropdown-item" href="{{ route('orders.create') }}">Adicionar Novo</a>
                    </div>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
                @if (Route::has('register'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                </li>
                @endif @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                            document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/partials/paginate.blade.php
<div class="form-group mb-0">
    <label for="paged">Itens por Página</label>
    <select class="form-control form-control-sm" name="paged" id="paged">
        <option value="" {{ request()->get('paged') == null ? 'selected' : ''}}>Todos</option>
        <option value="20" {{ request()->get('paged') == 20 ? 'selected' : ''}}>20</option>
        <option value="30" {{ request()->get('paged') == 30 ? 'selected' : ''}}>30</option>
        <option value="40" {{ request()->get('paged') == 40 ? 'selected' : ''}}>40</option>
        <option value="50" {{ request()->get('paged') == 50 ? 'selected' : ''}}>50</option>
    </select>
</div>