routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false
]);

Route::middleware(['auth'])
    ->group(function () {
        Route::get('/', 'HomeController@index')->name('home');

        // Clients
        Route::get('clients/filter', 'ClientController@filter')->name('clients.filter');
        Route::post('clients/bulk-destroy', 'ClientController@bulkDestroy')->name('clients.bulk-destroy');
        Route::resource('clients', 'ClientController');

        // Products
        Route::get('products/filter', 'ProductController@filter')->name('products.filter');
        Route::post('products/bulk-destroy', 'ProductController@bulkDestroy')->name('products.bulk-destroy');
        Route::resource('products', 'ProductController');

        // Orders
        Route::get('orders/add-to-cart', 'OrderController@addToCart');
        Route::get('orders/remove-from-cart', 'OrderController@removeFromCart');
        Route::get('orders/filter', 'OrderController@filter')->name('orders.filter');
        Route::get('orders/paginate', 'OrderController@paginate')->name('orders.paginate');
        Route::post('orders/bulk-destroy', 'OrderController@bulkDestroy')->name('orders.bulk-destroy');
        Route::resource('orders', 'OrderController');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 
        'price',
        'bar_code',
    ];

    /**
     * Get the formated client's cpf.
     *
     * @return string
     */
    public function getPriceFullAttribute()
    {
        return number_format($this->price, 2, ',' , '.');
    }

    /**
     * Get the orders record's associated with the product.
     */
    public function orders()
    {
        return $this->belongsToMany(Order::class, 'order_products');
    }
}

app/Http/Controllers/Api/V1/ProductController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProductCreateRequest;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function list()
    {
        $products = Product::all();
        
        return response()->json($products, Response::HTTP_OK);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductCreateRequest $request, Product $product)
    {
        DB::transaction(function () use ($request, $product) {
            $product->fill($request->all())
                ->save();
        });

        
        return response()->json($product, Response::HTTP_CREATED);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        
        if ($product) {
            return response()->json($product, Response::HTTP_FOUND);
        }

        return response()->json([], Response::HTTP_NOT_FOUND);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductCreateRequest $request, Product $product)
    {
        DB::transaction(function () use ($request, $product) {
           $product->update($request->all());
        });

        return response()->json($product, Response::HTTP_OK);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        DB::transaction(function () use ($product) {
            $product->delete();
        });

        return response()->json(true, Response::HTTP_OK);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductCreateRequest;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('name')
            ->paginate(20);
        
        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.manage');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  ProductCreateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductCreateRequest $request, Product $product)
    {
        DB::transaction(function () use ($request, $product) {
            $product->fill($request->all())
                ->save();
        });

        return redirect()
            ->route('products.create')
            ->with('success', 'Produto criado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  Product $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Product $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('product.manage', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  ProductCreateRequest  $request
     * @param  Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductCreateRequest $request, Product $product)
    {
        DB::transaction(function () use ($request, $product) {
            $product->update($request->all());
        });

        return redirect()
            ->route('products.edit', $product->id)
            ->with('success', 'Produto atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Product $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        DB::transaction(function () use ($product) {
            $product->delete();
        });

        return redirect()
            ->route('products.index')
            ->with('success', 'Produto removido com sucesso!');
    }

    /**
     * Remove the specifieds resources from storage.
     *
     * @param  Request  $request
     * @param  Product  $product
     * @return \Illuminate\Http\Response
     */
    public function bulkDestroy(Request $request, Product $product)
    {
        $ids = $request->input('bulk');

        DB::transaction(function () use ($ids, $product) {
            $product->whereIn('id', $ids)
                ->delete();
        });

        return response()->json(['status' => true], 200);
    }

    /**
     * Filter products
     *
     * @param  Request $request
     * @param  Product $client
     *
     * @return \Illuminate\Http\Response
     */
    public function filter(Request $request, Product $product)
    {
        $page = $request->input('paged') ?? 20;
        $search = $request->input('search');
        $filters = $request->input('filter');
        $orderBy = $request->input('order');
        $sortBy = $request->input('sort');
        
        $query = $product->newQuery();

        if ($filters) {
            if (in_array('name', $filters)) {
                $query->where('name', 'LIKE', '%' . $search . '%');
            }
    
            if (in_array('price', $filters)) {
                $query->where('price', 'LIKE', '%' . $search . '%');
            }
            
            if (in_array('bar_code', $filters)) {
                $query->where('bar_code', 'LIKE', '%' . $search . '%');
            }
        }

        if ($orderBy && $sortBy) {
            $query->orderBy($orderBy, $sortBy);
        }
        
        $products = $query->paginate($page)
            ->appends($request->except('page'));
        
        return view('product.index', compact('products'));
    }
}

resources/views/product/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 mb-3">
                @component('components.card')
                    <div class="row align-items-center">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <h3 class="mb-0">Lista de Produtos</h3>
                        </div>

                        <div class="col-sm-6 text-sm-right">
                            <a class="btn btn-success" href="{{ route('products.create') }}">Adicionar Produto</a>
                        </div>
                    </div>
                @endcomponent
            </div>

            <div class="col-12 mb-3">
                <form action="{{ route('products.filter') }}" method="get">
                    <div class="row">
                        <div class="col-12 mb-3">
                            @component('components.card')
                                @include('partials.filter', [
                                    'count_results' => request()->get('filter') ? $products->count() : '',
                                    'options' => [
                                        'name' => 'Nome',
                                        'price' => 'Preço',
                                        'bar_code' => 'Código de Barras',
                                    ],
                                    'placeholder' => 'Busque pelo nome, preço ou código de barras do produto.'
                                ])
                            @endcomponent
                        </div>

                        <div class="col-12 col-sm-2 mb-2">
                            @include('partials.paginate')
                        </div>

                        <div class="col-12 col-sm-3 col-md-3 d-flex align-items-end mb-2">
                            @include('partials.bulk-actions', [
                                'actions' => [
                                    'delete' => route('products.bulk-destroy')
                                ]
                            ])
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-12">
                @if (isset($products))
                    @component('components.table')
                        <thead>
                            <th class="d-none">
                                <input id="bulk-check-all" type="checkbox">
                            </th>
                            <th>
                                <a class="text-muted" href="{{ route('products.filter', ['order' => 'name', 'sort' => request()->get('sort') == 'asc' ? 'desc' : 'asc']) }}">Nome</a>
                            </th>
                            <th>
                                <a class="text-muted" href="{{ route('products.filter', ['order' => 'price', 'sort' => request()->get('sort') == 'asc' ? 'desc' : 'asc']) }}">Preço</a>
                            </th>
                            <th>
                                <a class="text-muted" href="{{ route('products.filter', ['order' => 'bar_code', 'sort' => request()->get('sort') == 'asc' ? 'desc' : 'asc']) }}">Código de Barras</a>
                            </th>
                            <th></th>
                        </thead>

                        <tbody>
                            @foreach ($products as $product)    
                                <tr>
                                    <td class="d-none">
                                        <input class="bulk-check" type="checkbox" name="bulk[{{ $product->id }}]" value="{{ $product->id }}">
                                    </td>
                                    <td>{{ $product->name }}</td>
                                    <td>R$ {{ $product->price_full }}</td>
                                    <td>{{ $product->bar_code }}</td>
                                    <td class="text-center text-md-right">
                                        <a class="btn btn-sm btn-primary mb-2 mb-md-0" href="{{ route('products.edit', $product->id) }}">Editar</a>
                                        <button class="btn btn-sm btn-danger" type="button" data-action="{{ route('products.destroy', $product->id) }}" data-toggle="modal" data-target="#modalDestroyConfirm">Remover</button>
                                    </td>
                                </tr>
                            @endforeach          
                        </tbody>
                    @endcomponent

                    <div class="d-flex justify-content-center mt-3">
                        {{ $products->links() }}
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

@push('modal')
    @include('includes.modal-destroy-confirm')
@endpush

resources/views/product/manage.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 mb-3">
                @component('components.card')    
                    <div class="row align-items-center">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <h3 class="mb-0">{{ ! isset($product) ? 'Cadastrar' : 'Atualizar' }} Produto</h3>
                        </div>

                        <div class="col-sm-6 text-sm-right">
                            <a class="btn btn-primary" href="{{ route('products.index') }}">Listar Produtos</a>
                        </div>
                    </div>
                @endcomponent      
            </div>

            <div class="col-12">
                @component('components.card')    
                    <form action="{{ ! isset($product) ? route('products.store') : route('products.update', $product->id) }}" method="post">
                        @csrf

                        @isset($product)
                            @method('PUT')
                        @endisset

                        <div class="form-row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label for="name">Nome</label>
                                    <input id="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" value="{{ old('name', $product->name ?? '') }}" placeholder="Digite o nome">
                                    @include('includes.form.validate', ['name' => 'name'])
                                </div>
                            </div>
                            
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="price">Preço</label>
                                    <input id="price" class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}" type="number" name="price" value="{{ old('price', $product->price ?? '') }}" step="0.01" placeholder="Digite o preço">
                                    @include('includes.form.validate', ['name' => 'price'])
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="bar_code">Código de Barras</label>
                                    <input id="bar_code" class="form-control {{ $errors->has('bar_code') ? 'is-invalid' : '' }}" type="text" name="bar_code" value="{{ old('bar_code', $product->bar_code ?? '') }}" maxlength="20" placeholder="Digite o código de barras">
                                    @include('includes.form.validate', ['name' => 'bar_code'])
                                </div>
                            </div>

                            <div class="col-12">
                                <div class="form-group text-right mb-0">
                                    @include('includes.form.submit')
                                </div>
                            </div>
                        </div>
                    </form>
                @endcomponent      
            </div>
        </div>
    </div>
@endsection