routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false
]);

Route::middleware(['auth'])
    ->group(function () {
        Route::get('/', 'HomeController@index')->name('home');

        // Clients
        Route::get('clients/filter', 'ClientController@filter')->name('clients.filter');
        Route::post('clients/bulk-destroy', 'ClientController@bulkDestroy')->name('clients.bulk-destroy');
        Route::resource('clients', 'ClientController');

        // Products
        Route::get('products/filter', 'ProductController@filter')->name('products.filter');
        Route::post('products/bulk-destroy', 'ProductController@bulkDestroy')->name('products.bulk-destroy');
        Route::resource('products', 'ProductController');

        // Orders
        Route::get('orders/add-to-cart', 'OrderController@addToCart');
        Route::get('orders/remove-from-cart', 'OrderController@removeFromCart');
        Route::get('orders/filter', 'OrderController@filter')->name('orders.filter');
        Route::get('orders/paginate', 'OrderController@paginate')->name('orders.paginate');
        Route::post('orders/bulk-destroy', 'OrderController@bulkDestroy')->name('orders.bulk-destroy');
        Route::resource('orders', 'OrderController');
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'name', 
        'email',
        'cpf',
    ];

    /**
     * Get the user record associated with the client.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get the order records associated with the client.
     */
    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function getAllOrderByName(Type $var = null)
    {
        return $this->orderBy('name')
            ->get();
    }

    /**
     * Get the formated client's cpf.
     *
     * @return string
     */
    public function getCpfFullAttribute()
    {
        return preg_replace("/(\d{3})(\d{3})(\d{3})(\d{2})/", "\$1.\$2.\$3-\$4", $this->cpf);
    }
}

app/Http/Controllers/Api/V1/ClientController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Http\Requests\ClientCreateRequest;
use App\Http\Requests\ClientUpdateRequest;
use App\Models\Client;
use Illuminate\Foundation\Auth\User;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;

class ClientController extends Controller
{
    /**
     * Return a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function list()
    {
        $clients = Client::all();
        
        return response()->json($clients, Response::HTTP_OK);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClientCreateRequest $request, Client $client)
    {
        DB::transaction(function () use ($request, $client) {
            $user = User::find($request->input('user_id'));

            $client->user()
                ->associate($user)
                ->fill($request->all())
                ->save();

            $client->unsetRelation('user');
        });

        
        return response()->json($client, Response::HTTP_CREATED);
    }

    /**
     * Display the specified resource.
     *
     * @param  id  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $client = Client::find($id);
        
        if ($client) {
            return response()->json($client, Response::HTTP_FOUND);
        }

        return response()->json([], Response::HTTP_NOT_FOUND);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(ClientUpdateRequest $request, Client $client)
    {
        DB::transaction(function () use ($request, $client) {
            $client->update($request->all());
        });

        return response()->json($client, Response::HTTP_OK);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        DB::transaction(function () use ($client) {
            $client->delete();
        });

        return response()->json(true, Response::HTTP_OK);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ClientCreateRequest;
use App\Http\Requests\ClientUpdateRequest;
use App\Models\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Auth::user()
            ->clients()
            ->orderBy('name')
            ->paginate(20);
        
        return view('client.index', compact('clients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.manage');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  ClientCreateRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClientCreateRequest $request, Client $client)
    {
        $authUser = Auth::user();

        DB::transaction(function () use ($request, $client, $authUser) {
            $client->user()
                ->associate($authUser)
                ->fill($request->all())
                ->save();
        });

        return redirect()
            ->route('clients.create')
            ->with('success', 'Cliente criado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        return view('client.show', compact('client'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('client.manage', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  ClientUpdateRequest  $request
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(ClientUpdateRequest $request, Client $client)
    {
        DB::transaction(function () use ($request, $client) {
            $client->update($request->all());
        });

        return redirect()
            ->route('clients.edit', $client->id)
            ->with('success', 'Cliente atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(Client $client)
    {
        DB::transaction(function () use ($client) {
            $client->delete();
        });

        return redirect()
            ->route('clients.index')
            ->with('success', 'Cliente removido com sucesso!');
    }

    /**
     * Remove the specifieds resources from storage.
     *
     * @param  Request  $request
     * @param  Client  $client
     * @return \Illuminate\Http\Response
     */
    public function bulkDestroy(Request $request, Client $client)
    {
        $ids = $request->input('bulk');

        DB::transaction(function () use ($ids, $client) {
            $client->whereIn('id', $ids)
                ->delete();
        });

        return response()->json(['status' => true], 200);
    }

    /**
     * Filter clients
     *
     * @param  Request $request
     * @param  Client $client
     *
     * @return \Illuminate\Http\Response
     */
    public function filter(Request $request, Client $client)
    {
        $page = $request->input('paged') ?? 20;
        $search = $request->input('search');
        $filters = $request->input('filter');
        $orderBy = $request->input('order');
        $sortBy = $request->input('sort');
        
        $query = $client->newQuery()
            ->where('user_id', Auth::user()->id);

        if ($filters) {
            if (in_array('name', $filters)) {
                $query->where('name', 'LIKE', '%' . $search . '%');
            }
    
            if (in_array('email', $filters)) {
                $query->where('email', 'LIKE', '%' . $search . '%');
            }
            
            if (in_array('cpf', $filters)) {
                $query->where('cpf', 'LIKE', '%' . $search . '%');
            }
        }

        if ($orderBy && $sortBy) {
            $query->orderBy($orderBy, $sortBy);
        }

        $clients = $query->paginate($page)
            ->appends($request->except('page'));
        
        return view('client.index', compact('clients'));
    }
}

resources/views/client/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 mb-3">
                @component('components.card')
                    <div class="row align-items-center">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <h3 class="mb-0">Lista de Clientes</h3>
                        </div>

                        <div class="col-sm-6 text-sm-right">
                            <a class="btn btn-success" href="{{ route('clients.create') }}">Adicionar Cliente</a>
                        </div>
                    </div>
                @endcomponent
            </div>

            <div class="col-12 mb-3">
                <form action="{{ route('clients.filter') }}" method="get">
                    <div class="row">
                        <div class="col-12 mb-3">
                            @component('components.card')
                                @include('partials.filter', [
                                    'count_results' => request()->get('filter') ? $clients->count() : '',
                                    'options' => [
                                        'name' => 'Nome',
                                        'email' => 'E-mail',
                                        'cpf' => 'CPF',
                                    ],
                                    'placeholder' => 'Busque pelo nome, e-mail ou cpf do cliente.'
                                ])
                            @endcomponent
                        </div>

                        <div class="col-12 col-sm-3 col-md-2 mb-2">
                            @include('partials.paginate')
                        </div>
                            
                        <div class="col-12 col-sm-3 col-md-3 d-flex align-items-end mb-2">
                            @include('partials.bulk-actions', [
                                'actions' => [
                                    'delete' => route('clients.bulk-destroy')
                                ]
                            ])
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-12">
                @if (isset($clients))
                    @component('components.table')
                        <thead>
                            <th class="d-none">
                                <input id="bulk-check-all" type="checkbox">
                            </th>
                            <th>
                                <a class="text-muted" href="{{ route('clients.filter', ['order' => 'name', 'sort' => request()->get('sort') == 'asc' ? 'desc' : 'asc']) }}">Nome</a>
                            </th>
                            <th>
                                <a class="text-muted" href="{{ route('clients.filter', ['order' => 'email', 'sort' => request()->get('sort') == 'asc' ? 'desc' : 'asc']) }}">E-mail</a>
                            </th>
                            <th>
                                <a class="text-muted" href="{{ route('clients.filter', ['order' => 'cpf', 'sort' => request()->get('sort') == 'asc' ? 'desc' : 'asc']) }}">CPF</a>
                            </th>
                            <th></th>
                        </thead>

                        <tbody>
                            @foreach ($clients as $client)    
                                <tr>
                                    <td class="d-none">
                                        <input class="bulk-check" type="checkbox" name="bulk[{{ $client->id }}]" value="{{ $client->id }}">
                                    </td>
                                    <td>
                                        <a href="{{ route('clients.show', $client->id) }}">{{ $client->name }}</a>
                                    </td>
                                    <td>{{ $client->email }}</td>
                                    <td>{{ $client->cpf_full }}</td>
                                    <td class="text-center text-lg-right">
                                        <a class="btn btn-sm btn-primary mb-2 mb-lg-0" href="{{ route('clients.edit', $client->id) }}">Editar</a>
                                        <button class="btn btn-sm btn-danger" type="button" data-action="{{ route('clients.destroy', $client->id) }}" data-toggle="modal" data-target="#modalDestroyConfirm">Remover</button>
                                    </td>
                                </tr>
                            @endforeach          
                        </tbody>
                    @endcomponent

                    <div class="d-flex justify-content-center mt-3">
                        {{ $clients->links() }}
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

@push('modal')
    @include('includes.modal-destroy-confirm')
@endpush

resources/views/client/manage.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 mb-3">
                @component('components.card')    
                    <div class="row align-items-center">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <h3 class="mb-0">{{ ! isset($client) ? 'Cadastrar' : 'Atualizar' }} Cliente</h3>
                        </div>

                        <div class="col-sm-6 text-sm-right">
                            <a class="btn btn-primary" href="{{ route('clients.index') }}">Listar Clientes</a>
                        </div>
                    </div>
                @endcomponent      
            </div>

            <div class="col-12">
                @component('components.card')    
                    <form action="{{ ! isset($client) ? route('clients.store') : route('clients.update', $client->id) }}" method="post">
                        @csrf

                        @isset($client)
                            @method('PUT')
                        @endisset

                        <div class="form-row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="name">Nome</label>
                                    <input id="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" value="{{ old('name', $client->name ?? '') }}" placeholder="Digite o nome">
                                    @include('includes.form.validate', ['name' => 'name'])
                                </div>
                            </div>
                            
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="cpf">CPF</label>
                                    <input id="cpf" class="form-control {{ $errors->has('cpf') ? 'is-invalid' : '' }}" type="text" name="cpf" value="{{ old('cpf', $client->cpf ?? '') }}" placeholder="Digite o CPF">
                                    @include('includes.form.validate', ['name' => 'cpf'])
                                </div>
                            </div>

                            <div class="col-12">
                                <div class="form-group">
                                    <label for="email">email</label>
                                    <input id="email" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}" type="email" name="email" value="{{ old('email', $client->email ?? '') }}" placeholder="Digite o email">
                                    @include('includes.form.validate', ['name' => 'email'])
                                </div>
                            </div>

                            <div class="col-12">
                                <div class="form-group text-right mb-0">
                                    @include('includes.form.submit')
                                </div>
                            </div>
                        </div>
                    </form>
                @endcomponent      
            </div>
        </div>
    </div>
@endsection

resources/views/client/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 mb-3">
                @component('components.card')
                    <div class="row align-items-center">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <h3 class="mb-0">Informações de Cliente</h3>
                        </div>

                        <div class="col-sm-6 text-sm-right">
                            <a class="btn btn-secondary" href="{{ route('clients.edit', $client->id) }}">Editar Cliente</a>
                            <a class="btn btn-primary" href="{{ route('clients.index') }}">Listar Clientes</a>
                        </div>
                    </div>
                @endcomponent
            </div>

            <div class="col-12">
                @component('components.table')
                    <tbody>
                        <tr>
                            <th>Nome</th>
                            <td>{{ $client->name }}</td>
                        </tr>
                        <tr>
                            <th>E-mail</th>
                            <td>{{ $client->email }}</td>
                        </tr>
                        <tr>
                            <th>CPF</th>
                            <td>{{ $client->cpf_full }}</td>
                        </tr>
                        <tr>
                            <th>Última Atualização</th>
                            <td>{{ $client->updated_at->format('d/m/Y \à\s H:i') }}</td>
                        </tr>
                    </tbody>
                @endcomponent
            </div>
        </div>
    </div>
@endsection