routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false
]);

Route::middleware(['auth'])
    ->group(function () {
        Route::get('/', 'HomeController@index')->name('home');

        // Clients
        Route::get('clients/filter', 'ClientController@filter')->name('clients.filter');
        Route::post('clients/bulk-destroy', 'ClientController@bulkDestroy')->name('clients.bulk-destroy');
        Route::resource('clients', 'ClientController');

        // Products
        Route::get('products/filter', 'ProductController@filter')->name('products.filter');
        Route::post('products/bulk-destroy', 'ProductController@bulkDestroy')->name('products.bulk-destroy');
        Route::resource('products', 'ProductController');

        // Orders
        Route::get('orders/add-to-cart', 'OrderController@addToCart');
        Route::get('orders/remove-from-cart', 'OrderController@removeFromCart');
        Route::get('orders/filter', 'OrderController@filter')->name('orders.filter');
        Route::get('orders/paginate', 'OrderController@paginate')->name('orders.paginate');
        Route::post('orders/bulk-destroy', 'OrderController@bulkDestroy')->name('orders.bulk-destroy');
        Route::resource('orders', 'OrderController');
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'status_id',
        'client_id',
        'number',
        'date_order',
        'discount',
    ];
    
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'date_order',
    ];

    /**
     * Get the status record associated with the order.
     */
    public function status()
    {
        return $this->belongsTo(Status::class);
    }

    /**
     * Get the client record associated with the order.
     */
    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    /**
     * Get the products record's associated with the order.
     */
    public function products()
    {
        return $this->belongsToMany(Product::class, 'order_products')
            ->withPivot(['price', 'quantity'])
            ->withTimestamps();
    }

    /**
     * Get the order's discount.
     *
     * @return string
     */
    public function getDiscountFullAttribute()
    {
        return number_format($this->discount, 2, ',', '.');
    }

    /**
     * Set the order's discount.
     *
     * @return string
     */
    public function setDiscountAttribute($value)
    {
        $this->attributes['discount'] = $value ? $value : 0.00;
    }

    /**
     * Get the order's total.
     *
     * @return string
     */
    public function getTotalAttribute()
    {
        $total = 0;
        $products = $this->products;
        
        foreach ($products as $product) {
            $total += $product->pivot->price * $product->pivot->quantity;
        }
        
        if ($this->discount < $total) {
            $total -= $this->discount;
        } else {
            $total = 0.00;
        }

        return number_format($total, 2, ',', '.');
    }

    /**
     * Get the oerder's user.
     * 
     * @param int $userId
     * 
     * @return int
     */
    public function getOrdersFromUser(int $userId)
    {
        return $this->wherehas('client', function ($q) use ($userId) {
            $q->where('user_id', $userId);
        })->count();
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 
        'price',
        'bar_code',
    ];

    /**
     * Get the formated client's cpf.
     *
     * @return string
     */
    public function getPriceFullAttribute()
    {
        return number_format($this->price, 2, ',' , '.');
    }

    /**
     * Get the orders record's associated with the product.
     */
    public function orders()
    {
        return $this->belongsToMany(Order::class, 'order_products');
    }
}

app/Http/Controllers/Api/V1/OrderController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Http\Requests\OrderCreateRequest;
use App\Http\Requests\OrderUpdateRequest;
use App\Models\Order;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     * 
     * @param int $clientId
     *
     * @return \Illuminate\Http\Response
     */
    public function list($clientId = null, Order $order)
    {
        $query = $order->newQuery();

        if ($clientId) {
            $orders = $query->where('client_id', $clientId);
        }

        $orders = $query->get();

        foreach ($orders as $order) {
            $order->total = $order->total;
        }
        
        return response()->json($orders, Response::HTTP_OK);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Order  $order
     * @return \Illuminate\Http\Response
     */
    public function store(OrderCreateRequest $request, Order $order)
    {
        $cart = $request->input('cart');
        $ids = array_column($request->input('cart'), 'product_id');
        
        DB::transaction(function () use ($request, $order, $cart, $ids) {
            $products = Product::whereIn('id', $ids)->get();
    
            foreach ($cart as $key => $item) {
                $cart[$key]['price'] = $products->firstWhere('id', $item['product_id'])->price;
            }

            $order->fill($request->all())
                ->save();
                
            $order->products()
                ->attach($cart);
        });

        $order->total = $order->total;
        
        return response()->json($order, Response::HTTP_CREATED);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::find($id);
        $order->total = $order->total;
        
        if ($order) {
            return response()->json($order, Response::HTTP_FOUND);
        }

        return response()->json([], Response::HTTP_NOT_FOUND);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  OrderUpdateRequest  $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(OrderUpdateRequest $request, Order $order)
    {
        $cart = $request->input('cart');
        $ids = array_column($request->input('cart'), 'product_id');
        
        DB::transaction(function () use ($request, $order, $cart, $ids) {
            $products = Product::whereIn('id', $ids)->get();
    
            foreach ($cart as $key => $item) {
                $cart[$key]['price'] = $products->firstWhere('id', $item['product_id'])->price;
            }

            $order->fill($request->all())
                ->save();
                
            $order->products()
                ->detach();

            $order->products()
                ->attach($cart);
        });

        $order->total = $order->total;
        
        return response()->json($order, Response::HTTP_CREATED);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        DB::transaction(function () use ($order) {
            $order->delete();
        });

        return response()->json(true, Response::HTTP_OK);
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\OrderCreateRequest;
use App\Http\Requests\OrderUpdateRequest;
use App\Models\Client;
use App\Models\Order;
use App\Models\Product;
use App\Models\Status;
use App\Services\CartService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Order $order)
    {
        $orders = $order->load(['status', 'client'])
            ->whereHas('client', function ($q) {
                $q->where('user_id', Auth::user()->id);
            })
            ->orderBy('date_order', 'desc')
            ->paginate(20);

        return view('order.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Client $client, CartService $cartService)
    {
        $cartService->removeCart();
        $statuses = Status::all();
        $products = Product::all();
        $clients = $client->getAllOrderByName();

        return view('order.manage', compact('statuses', 'products', 'clients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  OrderCreateRequest  $request
     * @param  Order  $order
     * @return \Illuminate\Http\Response
     */
    public function store(OrderCreateRequest $request, Order $order)
    {
        DB::transaction(function () use ($request, $order) {
            $order->fill($request->all())
                ->save();

            $order->products()
                ->attach($request->input('cart'));
        });

        return redirect()
            ->route('orders.create')
            ->with('success', 'Pedido criado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order, Client $client, CartService $cartService)
    {
        $statuses = Status::all();
        $products = Product::all();
        $clients = $client->getAllOrderByName();
        $order->load(['client', 'status']);
        $cartService->loadCart($order);

        // $order->putProductsInCart();

        return view('order.manage', compact('statuses', 'order', 'products', 'clients'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  OrderUpdateRequest $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(OrderUpdateRequest $request, Order $order)
    {
        DB::transaction(function () use ($request, $order) {
            $order->fill($request->all())
                ->save();

            $order->products()
                ->detach();

            $order->products()
                ->attach($request->input('cart'));
        });

        return redirect()
            ->route('orders.edit', $order->id)
            ->with('success', 'Pedido atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        DB::transaction(function () use ($order) {
            $order->delete();
        });

        return redirect()
            ->route('orders.index')
            ->with('success', 'Pedido removido com sucesso com sucesso!');
    }

    /**
     * Remove the specifieds resources from storage.
     *
     * @param  Request  $request
     * @param  Order  $order
     * @return \Illuminate\Http\Response
     */
    public function bulkDestroy(Request $request, Order $order)
    {
        $ids = $request->input('bulk');

        DB::transaction(function () use ($ids, $order) {
            $order->whereIn('id', $ids)
                ->delete();
        });

        return response()->json(['status' => true], 200);
    }

    /**
     * Filter orders.
     *
     * @param  Request $request
     * @param  Order $order
     * @param  Client $client
     *
     * @return \Illuminate\Http\Response
     */
    public function filter(Request $request, Order $order, Client $client)
    {
        $page = $request->input('paged') ?? 20;
        $search = $request->input('search');
        $filters = $request->input('filter');
        $orderBy = $request->input('order');
        $sortBy = $request->input('sort');
        
        $query = $order->newQuery()
            ->with('client')
            ->whereHas('client', function ($q) use ($search, $filters) {
                $q->where('clients.user_id', Auth::user()->id);

                    if ($filters && in_array('name', $filters)) {
                        $q->where('clients.name', 'LIKE', '%' . $search . '%');
                    }
            });
            
        if ($filters) {
            // Status
            if (in_array('status_id', $filters)) {
                $query->whereHas('status', function ($q) use ($search) {
                    $q->where('status.name', $search);
                });
            }
    
            // Number
            if (in_array('number', $filters)) {
                $query->where('orders.number', 'LIKE', '%' . $search . '%');
            }
    
            // Discount
            if (in_array('discount', $filters)) {
                $query->where('orders.discount', 'LIKE', '%' . $search . '%');
            }
    
            // Date Order
            if (in_array('date_order', $filters)) {
                $dateFilter = implode('-', array_reverse(explode('/', $search)));
                $query->whereDate('orders.date_order', 'LIKE', '%' . $dateFilter . '%');
            };
        }

        if ($orderBy && $sortBy) {
            $query->orderBy($orderBy, $sortBy);
        }

        $orders = $query->paginate($page)
            ->appends($request->except('page'));
        
        return view('order.index', compact('orders'));
    }

    /**
     * Add item to session cart.
     *
     * @param  Request $request
     * @param  CartService $cartService
     *
     * @return Illuminate\Http\Response
     */
    public function addToCart(Request $request, CartService $cartService)
    {
        $quantity = $request->input("quantity");
        $product = Product::find($request->input('product_id'));

        $cartService->addToCart($product, $quantity);
        $cart = $cartService->getCart();

        return response()->json([
            'status' => true,
            'cart' => $cart,
        ]);
    }

    /**
     * Remove item from session cart.
     *
     * @param  Request $request
     * @param  CartService $cartService
     *
     * @return Illuminate\Http\Response
     */
    public function removeFromCart(Request $request, CartService $cartService)
    {
        $cartService->removeFromCart($request->input('product_id'));
        $cart = $cartService->getCart();

        return response()->json([
            'status' => true,
            'cart' => $cart,
        ]);
    }
}

resources/views/order/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 mb-3">
                @component('components.card')
                    <div class="row align-items-center">
                        <div class="col-sm-6 mb-3 mb-sm-0">
                            <h3 class="mb-0">Lista de Pedidos</h3>
                        </div>

                        <div class="col-sm-6 text-sm-right">
                            <a class="btn btn-success" href="{{ route('orders.create') }}">Adicionar Pedido</a>
                        </div>
                    </div>
                @endcomponent
            </div>

            <div class="col-12 mb-3">
                <form action="{{ route('orders.filter') }}" method="get">
                    <div class="row">
                        <div class="col-12 mb-3">
                            @component('components.card')
                                @include('partials.filter', [
                                    'count_results' => request()->get('filter') ? $orders->count() : '',
                                    'options' => [
                                        'number' => 'Número do Pedido',
                                        'name' => 'Cliente',
                                        'date_order' => 'Data',
                                        'status_id' => 'Status',
                                        'discount' => 'Desconto',
                                    ],
                                    'placeholder' => 'Busque pelo número, cliente, data, status, desconto ou total do pedido.'
                                ])
                            @endcomponent
                        </div>

                        <div class="col-12 col-sm-2 mb-2">
                            @include('partials.paginate')
                        </div>

                        <div class="col-12 col-sm-3 col-md-3 d-flex align-items-end mb-2">
                            @include('partials.bulk-actions', [
                                'actions' => [
                                    'delete' => route('orders.bulk-destroy')
                                ]
                            ])
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-12">
                @if (isset($orders))
                    @component('components.table')
                        <thead>
                            <th class="d-none">
                                <input id="bulk-check-all" type="checkbox">
                            </th>
                            <th>
                                <a class="text-muted" href="{{ route('orders.filter', ['order' => 'number', 'sort' => request()->get('sort') == 'asc' ? 'desc' : 'asc']) }}">Número do Pedido</a>
                            </th>
                            <th>
                                <a class="text-muted" href="{{ route('orders.filter', ['order' => 'client_id', 'sort' => request()->get('sort') == 'asc' ? 'desc' : 'asc']) }}">Cliente</a>
                            </th>
                            <th>
                                <a class="text-muted" href="{{ route('orders.filter', ['order' => 'date_order', 'sort' => request()->get('sort') == 'asc' ? 'desc' : 'asc']) }}">Data do Pedido</a>
                            </th>
                            <th>
                                <a class="text-muted" href="{{ route('orders.filter', ['order' => 'status_id', 'sort' => request()->get('sort') == 'asc' ? 'desc' : 'asc']) }}">Status</a>
                            </th>
                            <th>
                                <a class="text-muted" href="{{ route('orders.filter', ['order' => 'discount', 'sort' => request()->get('sort') == 'asc' ? 'desc' : 'asc']) }}">Desconto</a>
                            </th>
                            <th class="text-muted">Total</th>
                            <th></th>
                        </thead>

                        <tbody>
                            @foreach ($orders as $order)
                                <tr>
                                    <td class="d-none">
                                        <input class="bulk-check" type="checkbox" name="bulk[{{ $order->id }}]" value="{{ $order->id }}">
                                    </td>
                                    <td>{{ $order->number }}</td>
                                    <td>
                                    <a href="{{ route('clients.show', $order->client->id) }}" target="_blank">{{ $order->client->name }}</a>
                                    </td>
                                    <td>{{ $order->date_order->format('d/m/Y') }}</td>
                                    <td>{{ $order->status->name }}</td>
                                    <td>R$ {{ $order->discount_full }}</td>
                                    <td>{{ $order->total }}</td>
                                    <td class="text-center text-lg-right">
                                        <a class="btn btn-sm btn-primary mb-2 mb-lg-0" href="{{ route('orders.edit', $order->id) }}">Editar</a>
                                        <button class="btn btn-sm btn-danger" type="button" data-action="{{ route('orders.destroy', $order->id) }}" data-toggle="modal" data-target="#modalDestroyConfirm">Remover</button>
                                    </td>
                                </tr>
                            @endforeach          
                        </tbody>
                    @endcomponent

                    <div class="d-flex justify-content-center mt-3">
                        {{ $orders->links() }}
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

@push('modal')
    @include('includes.modal-destroy-confirm')
@endpush